### ISSUE TITLE
arm64 support & question

### ISSUE THREAD

**Issue by otomay** [joesturge/lazymc-docker-proxy#122]
Hey! Could you support arm64 in the pre-built images, please?

running with latest build:
`exec /usr/local/bin/lazymc-docker-proxy: exec format error`

I builded locally on my arm64 device, but it didn't work, probably because of the cargo build targeting x86_64.

```
306.1   = note: cc: error: unrecognized command-line option '-m64'
306.1           
306.1 
306.2 warning: `lazymc-docker-proxy` (bin "lazymc-docker-proxy") generated 1 warning
306.2 error: could not compile `lazymc-docker-proxy` (bin "lazymc-docker-proxy") due to 1 previous error; 1 warning emitted
------

 4 warnings found (use docker --debug to expand):
 - FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 6)
 - FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 18)
 - FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 30)
 - FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 41)
Dockerfile:38
--------------------
  36 |     COPY Cargo.toml Cargo.lock ./
  37 |     COPY src ./src
  38 | >>> RUN cargo build --target x86_64-unknown-linux-musl --release --locked
  39 |     
  40 |     # health init
--------------------
ERROR: failed to solve: process "/bin/sh -c cargo build --target x86_64-unknown-linux-musl --release --locked" did not complete successfully: exit code: 101
```

and my question:

      # you should mount the minecraft server dir under /server, using read only.
      - data:/server:ro

can I just point to the same volume /data of "mc" service? or should I point to specific server folder?

thanks!

**Comment by joesturge** [comment]
Hi @otomay thanks for opening the issue, yep we can make this support arm, to your question, you can mount the same volume in multiple containers, that how it is done in the example, and it would work if you do ro in one place and rw in another

**Comment by otomay** [comment]
Thank you! I tried to contribute by forking, but got stuck.
I edited the Dockerfile to adjust the cargo build to identify the arch, but I got rust errors when running and I know nothing about rust :/

IDK if help, but I'll share what have I done:

```Dockerfile
ARG LAZYMC_VERSION=0.2.11
ARG LAZYMC_LEGACY_VERSION=0.2.10

FROM busybox:1.37.0-uclibc as downloader

ARG TARGETARCH
ARG LAZYMC_VERSION
ENV LAZYMC_VERSION=$LAZYMC_VERSION
RUN if [ "$TARGETARCH" = "amd64" ]; then \
        wget https://github.com/timvisee/lazymc/releases/download/v${LAZYMC_VERSION}/lazymc-v${LAZYMC_VERSION}-linux-x64 -O /lazymc; \
    elif [ "$TARGETARCH" = "arm64" ]; then \
        wget https://github.com/timvisee/lazymc/releases/download/v${LAZYMC_VERSION}/lazymc-v${LAZYMC_VERSION}-linux-aarch64 -O /lazymc; \
    elif [ "$TARGETARCH" = "armv7" ]; then \
        wget https://github.com/timvisee/lazymc/releases/download/v${LAZYMC_VERSION}/lazymc-v${LAZYMC_VERSION}-linux-armv7 -O /lazymc; \
    fi

RUN chmod +x /lazymc

ARG LAZYMC_LEGACY_VERSION
ENV LAZYMC_LEGACY_VERSION=$LAZYMC_LEGACY_VERSION
RUN if [ "$TARGETARCH" = "amd64" ]; then \
        wget https://github.com/timvisee/lazymc/releases/download/v${LAZYMC_LEGACY_VERSION}/lazymc-v${LAZYMC_LEGACY_VERSION}-linux-x64 -O /lazymc-legacy; \
    elif [ "$TARGETARCH" = "arm64" ]; then \
        wget https://github.com/timvisee/lazymc/releases/download/v${LAZYMC_LEGACY_VERSION}/lazymc-v${LAZYMC_LEGACY_VERSION}-linux-aarch64 -O /lazymc-legacy; \
    elif [ "$TARGETARCH" = "armv7" ]; then \
        wget https://github.com/timvisee/lazymc/releases/download/v${LAZYMC_LEGACY_VERSION}/lazymc-v${LAZYMC_LEGACY_VERSION}-linux-armv7 -O /lazymc-legacy; \
    fi

RUN chmod +x /lazymc-legacy

# build this app
FROM rust:1.81 as app-builder
RUN rustup target add x86_64-unknown-linux-musl aarch64-unknown-linux-musl
RUN apt update && apt install -y musl-tools musl-dev
RUN update-ca-certificates
RUN apt-get update && apt-get install -y pkg-config libssl-dev
WORKDIR /usr/src/lazymc-docker-proxy
COPY Cargo.toml Cargo.lock ./
COPY src ./src
ARG TARGETARCH
RUN if [ "$TARGETARCH" = "amd64" ]; then \
        cargo build --target x86_64-unknown-linux-musl --release --locked; \
    elif [ "$TARGETARCH" = "arm64" ]; then \
        cargo build --target aarch64-unknown-linux-musl --release --locked; \
    fi

FROM busybox:1.37.0-uclibc as health-init
RUN mkdir -p /app && echo "STARTING" > /app/health

FROM busybox:1.37.0-uclibc

ARG TARGETARCH
ARG LAZYMC_VERSION
ENV LAZYMC_VERSION=$LAZYMC_VERSION
ARG LAZYMC_LEGACY_VERSION
ENV LAZYMC_LEGACY_VERSION=$LAZYMC_LEGACY_VERSION

COPY --from=downloader /lazymc /usr/local/bin/lazymc
COPY --from=downloader /lazymc-legacy /usr/local/bin/lazymc-legacy
COPY --from=app-builder /usr/src/lazymc-docker-proxy/target/${TARGETARCH/arm64/aarch64}-unknown-linux-musl/release/lazymc-docker-proxy /usr/local/bin/lazymc-docker-proxy
COPY --from=health-init /app/health /app/health

WORKDIR /app

HEALTHCHECK --start-period=1m --interval=5s --retries=24 CMD ["lazymc", "--health"]

ENTRYPOINT ["lazymc-docker-proxy"]

```

I just downloaded the pre-build binaries instead of building like you to speed things up on my testings. But maybe it can be worth to use like that? idk

and the the logs from lazymc container (where I got stucked):

```
 INFO  lazymc-docker-proxy::entrypoint > Ensuring all server containers are stopped...
 INFO  lazymc-docker-proxy::entrypoint > Starting lazymc process for group: mc...
thread 'main' panicked at src/entrypoint/mod.rs:35:14:
called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by taukakao** [comment]
Replacing every instance of "x86_64-unknown-linux-musl" with "aarch64-unknown-linux-musl" in the original Dockerfile did in fact work for me. 

Not sure how to actually implement this in the CI but hope this helps.

**Comment by taukakao** [comment]
> Did you run the container?

Yeah, I have a similar setup.

I'm guessing the binaries are built for glibc, not musl, so I wouldn't expect them to work with the original Dockerfile. But no idea why building it yourself didn't work for you. 🤔

**Comment by otomay** [comment]
Me too hahaha but maybe I'm the one doing something wrong. But for now it fits my needs. My main concern was about image size, but even with ubuntu I got only 82.1MB, so good to go. I'll wait for oficial support to switch from this.

Thanks again man, good gaming for us!

**Comment by joesturge** [comment]
Thanks @otomay and @taukakao for investigating this! It sounds like you are very close to finding a solution to this, I have some ideas about CI integration, would be good if when we get it building for both platforms, the tests actions can be updated to have a matrix to run the suite against both platforms too. But let me know if you would like a hand setting that up when you get there!

**Comment by taukakao** [comment]
Btw. if you wanna help out @otomay you could build and test this Dockerfile https://github.com/taukakao/lazymc-docker-proxy/blob/master/Dockerfile 

You could also use the image `ghcr.io/taukakao/lazymc-docker-proxy:latest` but that would be risky for you since the container has unsandboxed root access to your system in this configuration.

**Comment by otomay** [comment]
@taukakao it worked both ways

I can't test connecting to the server rn, but building and pulling from your repo started the container successfully. I'm gonna try to connect to it later and let you know.

cheers

**Comment by taukakao** [comment]
thanks

**Comment by joesturge** [comment]
You could try using the build workflow on a GH arm runner like this example: https://learn.arm.com/learning-paths/cross-platform/github-arm-runners/actions/

using an os matrix for the build and test stages may simplify this

**Comment by taukakao** [comment]
@joesturge Weird, I'm guessing the arm runners existed at some point but don't anymore. 
The ubuntu-22.04-arm runner from the example doesn't and I also tried ubuntu-24.04-arm and ubuntu-latest-arm.
I can also not find anything about that in the official github docs.

So the only solutions here are cross compile or emulate I guess. 
I'm gonna try cross compilation with cross since emulation was very slow as mentioned in #143

**Comment by otomay** [comment]
update: all good. woke and connected to the server successfully!

and for workflows, here is a project that I follow that are for arm64 too: [Link](https://github.com/joaop221/v-rising-docker-arm64/blob/main/.github/workflows/docker-publish.yml)

this one doesn't use qemu and this one does: [Link](https://github.com/gogoout/vrising-server-arm64/blob/main/.github/workflows/docker-image.yml)

**Comment by taukakao** [comment]
@otomay Perfect, thank you for testing it out.

> and for workflows, here is a project that I follow that are for arm64 too: [Link](https://github.com/joaop221/v-rising-docker-arm64/blob/main/.github/workflows/docker-publish.yml)

I'm very confused by this, it seems to me like it's building an x64 container but it does in fact result in an arm64 container. I will need to check that out when I get the chance.

**Comment by taukakao** [comment]
I'm now convinced that [this](https://github.com/joaop221/v-rising-docker-arm64/blob/main/.github/workflows/docker-publish.yml) is also using emulation. It's also taking an hour and it uses RUN statements in the Dockerfile which can never work on a different architecture. 

I'm guessing installing QEMU manually is optional. Either it's already installed correctly or the buildx step installs it.

**Comment by taukakao** [comment]
More trouble shooting than anticipated but it's done.

**Comment by otomay** [comment]
hey, I just noticed a weird behavior, IDK if it is arm related.

I'm using `ghcr.io/taukakao/lazymc-docker-proxy:latest`

The application goes unhealthy every a few minutes when no one is connected. Once I connect I think it estabilzes, bc I can play without getting dc.

```
2024-11-04T11:43:09.572725088Z  INFO  lazymc-docker-proxy::entrypoint > Ensuring all server containers are stopped...
2024-11-04T11:43:09.582173301Z  INFO  lazymc-docker-proxy::entrypoint > Starting lazymc process for group: mc...
2024-11-04T11:43:09.582584425Z  INFO  lazymc-docker-proxy::health     > Application is healthy.
2024-11-04T11:43:09.599431509Z  INFO  mc::lazymc                      > Proxying public 0.0.0.0:25565 to server 172.22.0.3:25565
2024-11-04T11:46:39.000495130Z  ERROR mc::lazymc                      > Closing connection, error occurred
2024-11-04T11:46:39.000523770Z  ERROR lazymc-docker-proxy::health     > Application is unhealthy.
2024-11-04T11:48:42.678246945Z  INFO  lazymc-docker-proxy::entrypoint > Received exit signal. Stopping all server containers...
2024-11-04T11:48:43.179122774Z  INFO  lazymc-docker-proxy::entrypoint > Ensuring all server containers are stopped...
2024-11-04T11:48:43.184657548Z  INFO  lazymc-docker-proxy::entrypoint > Starting lazymc process for group: mc...
2024-11-04T11:48:43.186226564Z  INFO  lazymc-docker-proxy::health     > Application is healthy.
2024-11-04T11:48:43.188631147Z  INFO  mc::lazymc                      > Proxying public 0.0.0.0:25565 to server 172.22.0.3:25565
 ```

It goes like this in a loop 24/7.

In game I just noticed when starting the server through a connection, that sometimes it takes longer than other times. Maybe bc of the lazymc container restarting.

I went back to my local build [(here)](https://github.com/joesturge/lazymc-docker-proxy/issues/122#issuecomment-2446708612), and got the same results.

I seached for similar issues on lazymc repo and didn't find anything about it. Is this expected when no one is connected? Maybe I'm tripping.

**Comment by taukakao** [comment]
Hm, I don't have this problem so I think it's not an issue with all arm containers. 🤔
Did you set the correct protocol version?

**Comment by otomay** [comment]
are you talking about `lazymc.public.protocol=767` and `lazymc.public.version=1.21`?

well, at least in the multiplayer screen shows the right compatibility. Anything than that shows compatibility issue when server is sleeping.

but just tested without parsing these args and got the behavior again.

It's weird bc the log are from lazymc loosing a connection. But nothing was suposed to be connected.
when connected and playing, I got these errors periodically, but the container doesn't restart:

```
 WARN  mc::lazymc                      > Failed to proxy: Connection reset by peer (os error 104)
 WARN  mc::lazymc                      > Failed to proxy: Connection reset by peer (os error 104)
 ```

**Comment by taukakao** [comment]
I think it's a seperate issue. Maybe open a new on in this repo.

**Comment by otomay** [comment]
Thanks! I'll do a test with default values to see if persists
